export const devData = {
  loading: false,
  error: null,
  info: {
    id: "comp_67aad79b368ad",
    user_id: "user_67a156827ff8a",
    created_at: "2025-02-11 13:52:43",
    updated_at: "2025-02-11 13:52:43",
    type: "TRA",
    name: "テスト大会",
    date_from: "2025-02-12",
    date_to: "2025-02-12",
    venue: "テスト会場22",
    num_e: "6",
    panels: "3",
    team_by_cat: 1,
    read_d: 1,
    read_t: 1,
    read_h: 1,
    full_d: 0,
    full_t: 0,
    full_h: 0,
  },
  categories: [
    {
      id: "cat_67aad7ca4ea20",
      competition_id: "comp_67aad79b368ad",
      name: "Aクラス",
      rounds: "3",
      has_mix: 0,
      created_at: "2025-02-11 13:53:30",
      updated_at: "2025-02-11 13:53:30",
    },
    {
      id: "cat_67aad7ca5ba24",
      competition_id: "comp_67aad79b368ad",
      name: "Bクラス",
      rounds: "2",
      has_mix: 0,
      created_at: "2025-02-11 13:53:30",
      updated_at: "2025-02-11 13:53:30",
    },
    {
      id: "cat_67dc12bc604c8",
      competition_id: "comp_67aad79b368ad",
      name: "Cクラス",
      rounds: "1",
      has_mix: 0,
      created_at: "2025-02-17 15:48:29",
      updated_at: "2025-02-17 15:48:29",
    },
  ],
  rules: {
    qualify: [
      {
        id: "rule_67b32db208554",
        category_id: "cat_67aad7ca4ea20",
        routines: "2",
        is_total: 0,
      },
      {
        id: "rule_67b32db212996",
        category_id: "cat_67aad7ca5ba24",
        routines: "2",
        is_total: 0,
      },
    ],
    semifinal: [
      {
        id: "rule_67b32db693442",
        category_id: "cat_67aad7ca4ea20",
        routines: "2",
        is_total: 1,
      },
    ],
    final: [
      {
        id: "rule_67b32e2f810bf",
        category_id: "cat_67aad7ca4ea20",
        routines: "1",
        is_total: 0,
      },
      {
        id: "rule_67b32e2f8b77b",
        category_id: "cat_67aad7ca5ba24",
        routines: "1",
        is_total: 0,
      },
      {
        id: "rule_67dd5fe6d8b52",
        category_id: "cat_67dc12bc604c8",
        routines: "1",
        is_total: 0,
      },
    ],
  },
  routines: {
    qualify: [
      {
        id: "rtn_67ddf4c1c1848",
        category_id: "cat_67aad7ca4ea20",
        number: 1,
        round: "qualify",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
      {
        id: "rtn_67ddf4c1c1851",
        category_id: "cat_67aad7ca4ea20",
        number: 2,
        round: "qualify",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
      {
        id: "rtn_67ddf4c1c1853",
        category_id: "cat_67aad7ca5ba24",
        number: 1,
        round: "qualify",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
      {
        id: "rtn_67ddf4c1c1856",
        category_id: "cat_67aad7ca5ba24",
        number: 2,
        round: "qualify",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
    ],
    semifinal: [
      {
        id: "rtn_67ddf514d6550",
        category_id: "cat_67aad7ca4ea20",
        number: 1,
        round: "semifinal",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
      {
        id: "rtn_67ddf514d6558",
        category_id: "cat_67aad7ca4ea20",
        number: 2,
        round: "semifinal",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
    ],
    final: [
      {
        id: "rtn_67ddf53857b1d",
        category_id: "cat_67aad7ca4ea20",
        number: 1,
        round: "final",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },

      {
        id: "rtn_67ddf53857b26",
        category_id: "cat_67aad7ca5ba24",
        number: 1,
        round: "final",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
      {
        id: "rtn_67ddf53857b29",
        category_id: "cat_67dc12bc604c8",
        number: 1,
        round: "final",
        has_e: 1,
        has_d: 1,
        has_h: 1,
        has_t: 1,
      },
    ],
  },
  players: {
    individual: [
      {
        category_id: "cat_67aad7ca4ea20",
        players: [
          {
            id: "plyr_67b9a84b9c855",
            competition_id: "comp_67aad79b368ad",
            gender: "男子",
            name: "山田　太郎",
            phonetic: "やまだ　たろう",
            team: "テストチーム3",
            category_id: "cat_67aad7ca4ea20",
            grp: 1,
            number: 1,
            is_open: 0,
          },
          {
            id: "plyr_67b9a84ba9189",
            competition_id: "comp_67aad79b368ad",
            gender: "男子",
            name: "佐藤　次郎",
            phonetic: "さとう　じろう",
            team: "チームトラ2",
            category_id: "cat_67aad7ca4ea20",
            grp: 1,
            number: 2,
            is_open: 0,
          },
        ],
      },
      {
        category_id: "cat_67aad7ca5ba24",
        players: [
          {
            id: "plyr_67b9a84bb58a2",
            competition_id: "comp_67aad79b368ad",
            gender: "男子",
            name: "小林　三郎",
            phonetic: "こばやし　さぶろう",
            team: "虎チーム",
            category_id: "cat_67aad7ca5ba24",
            grp: 1,
            number: 1,
            is_open: 0,
          },
        ],
      },
      {
        category_id: "cat_67dc12bc604c8",
        players: [
          {
            id: "plyr_67de93151d450",
            competition_id: "cat_67dc12bc604c8",
            gender: "男子",
            name: "佐々木　四郎",
            phonetic: "ささき　しろう",
            team: "TeamTra",
            category_id: "cat_67dc12bc604c8",
            grp: 1,
            number: 1,
            is_open: 0,
          },
        ],
      },
    ],
    syncronized: [
      {
        category_id: "cat_67aad7ca4ea20",
        players: [
          {
            id: "plyr_67b9ac6be5e5b",
            competition_id: "comp_67aad79b368ad",
            category_id: "cat_67aad7ca4ea20",
            gender: "男子",
            grp: 1,
            number: 1,
            name: "山田　太郎2",
            phonetic: "やまだ　たろう",
            team: "テストチーム",
            name2: "中山　五郎",
            phonetic2: "なかやま　ごろう",
            team2: "テストチーム",
            is_open: 0,
          },
          {
            id: "plyr_67b9ac6bf3102",
            competition_id: "comp_67aad79b368ad",
            category_id: "cat_67aad7ca4ea20",
            gender: "男子",
            grp: 1,
            number: 2,
            name: "佐藤　次郎",
            phonetic: "さとう　じろう",
            team: "チームトラ",
            name2: "伊藤　六郎",
            phonetic2: "いとう　ろくろう",
            team2: "テストチーム",
            is_open: 0,
          },
        ],
      },
      {
        category_id: "cat_67aad7ca5ba24",
        players: [
          {
            id: "plyr_67b9ac6c0b888",
            competition_id: "comp_67aad79b368ad",
            category_id: "cat_67aad7ca5ba24",
            gender: "男子",
            grp: 1,
            number: 1,
            name: "小林　三郎",
            phonetic: "こばやし　さぶろう",
            team: "虎チーム",
            name2: "大林　七郎",
            phonetic2: "おおばやし　ななろう",
            team2: "テストチーム",
            is_open: 0,
          },
        ],
      },
      {
        category_id: "cat_67dc12bc604c8",
        players: [
          {
            id: "plyr_67b9ac6c18188",
            competition_id: "comp_67aad79b368ad",
            category_id: "cat_67dc12bc604c8",
            gender: "男子",
            grp: 1,
            number: 1,
            name: "佐々木　四郎",
            phonetic: "ささき　しろう",
            team: "TeamTra",
            name2: "小山　八郎",
            phonetic2: "こやま　はちろう",
            team2: "テストチーム",
            is_open: 0,
          },
        ],
      },
    ],
  },
};
